[build]
  command = "yarn build && yarn start" # the command you run to build this file
  functions = "lambda/build" # netlify-lambda builds to this folder AND Netlify reads functions from here
  publish = ".next" # create-react-app builds to this folder, Netlify should serve all these files statically